#!/bin/bash
#SBATCH -J TBSLAS
#SBATCH --export=ALL
#
# Options for Stampede
#SBATCH -p
# SBATCH -A <project>


WORK_DIR=${PWD}
cd ${WORK_DIR}

module load fftw3
export OMP_NUM_THREADS=16
export TBSLAS_RESULT_DIR=${WORK}/stokes_tc_2
mkdir -p ${TBSLAS_RESULT_DIR};

time ibrun tacc_affinity bin/stokes  -test_case 2 -pt_cnt 100 -pt_rad 0.15 -jump_width 1e-10 -rho 4.0e+6 -ref_tol 1e-10 -min_depth 1 -max_depth 5 -fmm_q 14 -fmm_m 10 -gmres_tol 2.5e-7 -gmres_iter 200 -ksp_gmr -tn $1

### End of script
